apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  selector:
    matchLabels:
      app: nginx-ui
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx-ui
    spec:
      containers:
      - name: nginx-ui
        image: justezy0210/nginx-ui:1.0.1
        ports:
        - containerPort: 80